(ns
  ^{:author "mikera"
    :doc "Special effects. Images can be generated by composing these functions."}  
  clisk.effects
  (:use [clisk node util functions colours patterns textures]))

(set! *warn-on-reflection* true)
(set! *unchecked-math* true)

(defn psychedelic 
  "Psychedelic colour effect"
  ([src]
    (adjust-hue (scale 0.2 noise) src)))

(defn monochrome
  "Converts to monochrome"
  ([src]
    (lightness-from-rgb src)))

(defn posterize
  ([src]
    (warp
      src 
      (v* 0.2 (vfloor (v* 5.0 pos))))))